export const ADD_NEW_ARTICLE = 'ADD_NEW_ARTICLE'
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL'
export const LOAD_ARTICLES = 'LOAD_ARTICLES'

export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START'
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTS_FAIL'
export const LOAD_COMMENTS = 'LOAD_COMMENTS'
