export const ADD_NEW_ARTICLE = 'ADD_NEW_ARTICLE'
export const ADD_NEW_COMMENT = 'ADD_NEW_COMMENT'
export const DELETE_COMMENT = 'DELETE_COMMENT'

export const LOAD_ARTICLES_START = 'LOAD_ARTICLES_START'
export const LOAD_ARTICLES_SUCCESS = 'LOAD_ARTICLES_SUCCESS'
export const LOAD_ARTICLES_FAIL = 'LOAD_ARTICLES_FAIL'
export const LOAD_ARTICLES = 'LOAD_ARTICLES'

export const LOAD_ARTICLE_BY_ID_START = 'LOAD_ARTICLE_BY_ID_START'
export const LOAD_ARTICLE_BY_ID_SUCCESS = 'LOAD_ARTICLE_BY_ID_SUCCESS'
export const LOAD_ARTICLE_BY_ID_FAIL = 'LOAD_ARTICLE_BY_ID_FAIL'
export const LOAD_ARTICLE_BY_ID = 'LOAD_ARTICLE_BY_ID'

export const LOAD_COMMENTS_START = 'LOAD_COMMENTS_START'
export const LOAD_COMMENTS_SUCCESS = 'LOAD_COMMENTS_SUCCESS'
export const LOAD_COMMENTS_FAIL = 'LOAD_COMMENTS_FAIL'
export const LOAD_COMMENTS = 'LOAD_COMMENTS'

export const LOAD_ALL_COMMENTS_START = 'LOAD_ALL_COMMENTS_START'
export const LOAD_ALL_COMMENTS_SUCCESS = 'LOAD_ALL_COMMENTS_SUCCESS'
export const LOAD_ALL_COMMENTS_FAIL = 'LOAD_ALL_COMMENTS_FAIL'
export const LOAD_ALL_COMMENTS = 'LOAD_ALL_COMMENTS'

export const LOAD_COMMENTS_PAGE_START = 'LOAD_COMMENTS_PAGE_START'
export const LOAD_COMMENTS_PAGE_SUCCESS = 'LOAD_COMMENTS_PAGE_SUCCESS'
export const LOAD_COMMENTS_PAGE_FAIL = 'LOAD_COMMENTS_PAGE_FAIL'
export const LOAD_COMMENTS_PAGE = 'LOAD_COMMENTS_PAGE'

export const ADD_USER = 'ADD_USER'